import type { Metadata } from "next";
import "./globals.css";
import { publicSans } from "@/fonts/fonts";
import FullscreenButton from "@/components/FullscreenButton/FullscreenButton";
import { ScrollbarThemer } from "@/components/ScrollbarThemer/ScrollbarThemer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${publicSans.className} antialiased`}>
        {children}
        <FullscreenButton />
        <ScrollbarThemer />
      </body>
    </html>
  );
}
